from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class CommercialMemorySignal:
    """Output contract of the Commercial Memory Salience Selector.

    Consumed by PromptBuilder to render human-readable continuity context.
    Not metadata. Not backend labels. Operational context for the AI seller.

    Generated by:  CommercialMemorySelector  (domain/memory/salience/selector.py)
    Consumed by:   PromptBuilderService      (infrastructure/ai/prompting/builder/prompt_builder.py)
    """

    # Natural continuity for the model (max ~2 sentences, no backend labels)
    continuity_brief: str = ""

    # Active commercial anchor for this turn (pain / objection / buy signal, human language)
    commercial_anchor_active: str = ""

    # Concrete episodic hook — only populated when context_weight == "strong"
    episodic_hook: str = ""

    # Context budget signal: "light" | "moderate" | "strong"
    # Controls: prompt layout, pricing compaction, memory position
    context_weight: str = "light"

    # Observability: which memory fields contributed to this signal
    memory_used: list[str] = field(default_factory=list)

    # Observability: how many memory candidates were scored
    candidates_evaluated: int = 0

    # Observability: how many were dropped below threshold
    candidates_dropped: int = 0
