[pytest]
filterwarnings =
    ignore::DeprecationWarning:sqlalchemy.sql.schema

# limitar descubrimiento de tests solo al directorio de tests para evitar ejecutar scripts que hacen I/O externo
testpaths = ../tests
addopts = -q -m "not integration and not e2e"
# evitar recorrer scripts que no son tests y que hacen I/O externo
norecursedirs = project/scripts scripts
markers =
    unit: pruebas unitarias puras
    integration: pruebas de integración entre capas
    e2e: pruebas extremo a extremo representativas
